[template]
src = "fluentd-collector.tmpl"
dest = "/etc/td-agent/config.d/zz-collector.conf"
prefix = "/%%PROJECT%%/%%ARENA%%"

keys = [
    "/config/AWSRegion",
    "/config/Arena",
    "/config/FluentLogsBucket",
    "/config/AccessLoggingBucket",
    "/config/SQS/Queue",
    "/config/SQS/AccessKey",
    "/config/SQS/SecretKey",
    "/config/SQS/Region",
    "/config/ElasticSearch/AWSEndpoint",
]

check_cmd  = ". /etc/profile.d/proxy.sh && /usr/sbin/td-agent --dry-run -c {{.src}}"
reload_cmd = "/etc/init.d/td-agent restart"
