[template]
src = "fluentd-collector.tmpl"
dest = "/etc/td-agent/config.d/collector.conf"
prefix = "/%%STACK%%/%%ENVIRONMENT%%"

keys = [
    "/config/AWSRegion",
    "/config/FluentLogsBucket",
    "/config/AccessLoggingBucket",
    "/config/SQS/Queue",
    "/config/SQS/AccessKey",
    "/config/SQS/SecretKey",
    "/config/SQS/Region",
    "/config/ElasticSearch/AWSEndpoint",
]

check_cmd  = "/usr/sbin/td-agent --dry-run -c {{.src}}"
reload_cmd = "/etc/init.d/td-agent restart"
