[template]
src = "fluentd-elb.tmpl"
dest = "/etc/td-agent/config.d/elb.conf"
prefix = "/%%STACK%%/%%ENVIRONMENT%%"

keys = [
    "/config/AWSRegion",
    "/config/AccessLoggingBucket",
]

check_cmd  = "/usr/sbin/td-agent --dry-run -c {{.src}}"
reload_cmd = "/etc/init.d/td-agent restart"

